//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من نحن.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نبذة مختصرة.
        /// </summary>
        internal static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة مستخدم جديد للنظام.
        /// </summary>
        internal static string AcessLimit {
            get {
                return ResourceManager.GetString("AcessLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الحساب.
        /// </summary>
        internal static string AcountType {
            get {
                return ResourceManager.GetString("AcountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل.
        /// </summary>
        internal static string ActiveAcount {
            get {
                return ResourceManager.GetString("ActiveAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضافة حساب.
        /// </summary>
        internal static string AddAcount {
            get {
                return ResourceManager.GetString("AddAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة.
        /// </summary>
        internal static string AddButon {
            get {
                return ResourceManager.GetString("AddButon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضيف من قبل.
        /// </summary>
        internal static string AddBy {
            get {
                return ResourceManager.GetString("AddBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التغير بنجاح.
        /// </summary>
        internal static string AddComplte {
            get {
                return ResourceManager.GetString("AddComplte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  الحضور اليومي.
        /// </summary>
        internal static string AddDaliyAttendance {
            get {
                return ResourceManager.GetString("AddDaliyAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدارة الحضور.
        /// </summary>
        internal static string AddDaliyAttendancem {
            get {
                return ResourceManager.GetString("AddDaliyAttendancem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل بيانات اولا.
        /// </summary>
        internal static string AddDateFirst {
            get {
                return ResourceManager.GetString("AddDateFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضافة درجات.
        /// </summary>
        internal static string AddDegress {
            get {
                return ResourceManager.GetString("AddDegress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الاضافة.
        /// </summary>
        internal static string ADDField {
            get {
                return ResourceManager.GetString("ADDField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأجراء لم ينجح.
        /// </summary>
        internal static string AddNotComplte {
            get {
                return ResourceManager.GetString("AddNotComplte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت العملية.
        /// </summary>
        internal static string AddNotComplte1 {
            get {
                return ResourceManager.GetString("AddNotComplte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضافة طلاب.
        /// </summary>
        internal static string AddStudent {
            get {
                return ResourceManager.GetString("AddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة  درجات الطلاب.
        /// </summary>
        internal static string AddStudentDegress {
            get {
                return ResourceManager.GetString("AddStudentDegress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت الاضافة بنجاح.
        /// </summary>
        internal static string ADDSuceess {
            get {
                return ResourceManager.GetString("ADDSuceess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الحساب.
        /// </summary>
        internal static string AdminAcountType {
            get {
                return ResourceManager.GetString("AdminAcountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة.
        /// </summary>
        internal static string AdminPassword {
            get {
                return ResourceManager.GetString("AdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمر.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سابقا بدأ العام الدراسي بتاريخ.
        /// </summary>
        internal static string AgoStartYearDays {
            get {
                return ResourceManager.GetString("AgoStartYearDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجميع.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجميع.
        /// </summary>
        internal static string ALlData {
            get {
                return ResourceManager.GetString("ALlData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع المواد.
        /// </summary>
        internal static string AllSubject {
            get {
                return ResourceManager.GetString("AllSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |JPG| GIF|  BMP |PNG|JPEG|PDF|DOCX|PPTX|ZIP صيغة الملف غير مقبولة الامتدادات المقبولة.
        /// </summary>
        internal static string AlowsFile {
            get {
                return ResourceManager.GetString("AlowsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        internal static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحضور.
        /// </summary>
        internal static string Attencane {
            get {
                return ResourceManager.GetString("Attencane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غائب.
        /// </summary>
        internal static string Attencaneno {
            get {
                return ResourceManager.GetString("Attencaneno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حاضر.
        /// </summary>
        internal static string Attencaneyes {
            get {
                return ResourceManager.GetString("Attencaneyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الحضور.
        /// </summary>
        internal static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقل من جهة اخرى.
        /// </summary>
        internal static string cameFrmoOther {
            get {
                return ResourceManager.GetString("cameFrmoOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتقل من جهة اخرى.
        /// </summary>
        internal static string CameFromOther {
            get {
                return ResourceManager.GetString("CameFromOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نجح من مرحلة سابقة.
        /// </summary>
        internal static string canmeFromOtherStage {
            get {
                return ResourceManager.GetString("canmeFromOtherStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكن الحذف لوجود بيانات مرتبطة بها.
        /// </summary>
        internal static string cannotdelet {
            get {
                return ResourceManager.GetString("cannotdelet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغير كلمة المرور.
        /// </summary>
        internal static string changepassword {
            get {
                return ResourceManager.GetString("changepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيبر.
        /// </summary>
        internal static string changepasswordnow {
            get {
                return ResourceManager.GetString("changepasswordnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أختر.
        /// </summary>
        internal static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر المواد.
        /// </summary>
        internal static string ChoseONe {
            get {
                return ResourceManager.GetString("ChoseONe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الطالب.
        /// </summary>
        internal static string choseStudent {
            get {
                return ResourceManager.GetString("choseStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكلية/ المدرسة.
        /// </summary>
        internal static string College {
            get {
                return ResourceManager.GetString("College", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جامعي/دراسات.
        /// </summary>
        internal static string collegeing {
            get {
                return ResourceManager.GetString("collegeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكن ارسال رسالة فارغة .
        /// </summary>
        internal static string CompleteInfo {
            get {
                return ResourceManager.GetString("CompleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدولة.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  |JPG| GIF|  BMP |PNG|JPEG صيغة الملف غير مقبولة الامتدادات المقبولة.
        /// </summary>
        internal static string custStatusInvalidFileUploaded {
            get {
                return ResourceManager.GetString("custStatusInvalidFileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من التاريخ.
        /// </summary>
        internal static string DataFrom {
            get {
                return ResourceManager.GetString("DataFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التسجيل.
        /// </summary>
        internal static string DataRecord {
            get {
                return ResourceManager.GetString("DataRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الى التاريخ.
        /// </summary>
        internal static string DataTo {
            get {
                return ResourceManager.GetString("DataTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الاجابة.
        /// </summary>
        internal static string DateAnuswer {
            get {
                return ResourceManager.GetString("DateAnuswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موعد الدرس.
        /// </summary>
        internal static string DateClass {
            get {
                return ResourceManager.GetString("DateClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Dead.
        /// </summary>
        internal static string DateDead {
            get {
                return ResourceManager.GetString("DateDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        internal static string DateDo {
            get {
                return ResourceManager.GetString("DateDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الطلب.
        /// </summary>
        internal static string DateRequest {
            get {
                return ResourceManager.GetString("DateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ العرض.
        /// </summary>
        internal static string DateStart {
            get {
                return ResourceManager.GetString("DateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ بدء الدورة.
        /// </summary>
        internal static string DateTutorialStart {
            get {
                return ResourceManager.GetString("DateTutorialStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صيغة التاريخ غير صحيحة.
        /// </summary>
        internal static string DateTypeIncorrect {
            get {
                return ResourceManager.GetString("DateTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الرفع.
        /// </summary>
        internal static string dateupload {
            get {
                return ResourceManager.GetString("dateupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير فعال.
        /// </summary>
        internal static string DeActive {
            get {
                return ResourceManager.GetString("DeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ايقاف تفعيل.
        /// </summary>
        internal static string DEActiveAcount {
            get {
                return ResourceManager.GetString("DEActiveAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موعد التسليم النهائي.
        /// </summary>
        internal static string DeadLine {
            get {
                return ResourceManager.GetString("DeadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجة.
        /// </summary>
        internal static string Degress {
            get {
                return ResourceManager.GetString("Degress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجة من.
        /// </summary>
        internal static string DegressFrom {
            get {
                return ResourceManager.GetString("DegressFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة الأمتحان  من يجب ان اعلى من صفر.
        /// </summary>
        internal static string degressFromErroLessone {
            get {
                return ResourceManager.GetString("degressFromErroLessone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف.
        /// </summary>
        internal static string DeleteDo {
            get {
                return ResourceManager.GetString("DeleteDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الحذف.
        /// </summary>
        internal static string DeleteField {
            get {
                return ResourceManager.GetString("DeleteField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم.
        /// </summary>
        internal static string Depart {
            get {
                return ResourceManager.GetString("Depart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم.
        /// </summary>
        internal static string Departmnt {
            get {
                return ResourceManager.GetString("Departmnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفاصيل.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المباشرة بالدراسة.
        /// </summary>
        internal static string DetermineLearnStartDay {
            get {
                return ResourceManager.GetString("DetermineLearnStartDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنزيل.
        /// </summary>
        internal static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تقصد.
        /// </summary>
        internal static string DoYouMean {
            get {
                return ResourceManager.GetString("DoYouMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية التعديل.
        /// </summary>
        internal static string EditField {
            get {
                return ResourceManager.GetString("EditField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل المواد التي سيدرسها وكذالك مستوى صلاحياته.
        /// </summary>
        internal static string edititLearnandLevel {
            get {
                return ResourceManager.GetString("edititLearnandLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل اسم طالب.
        /// </summary>
        internal static string EditStudentname {
            get {
                return ResourceManager.GetString("EditStudentname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل.
        /// </summary>
        internal static string EditSucess {
            get {
                return ResourceManager.GetString("EditSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسمى الوضيفي.
        /// </summary>
        internal static string EducationLeve {
            get {
                return ResourceManager.GetString("EducationLeve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الألكتروني.
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        internal static string emailAddress {
            get {
                return ResourceManager.GetString("emailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الألكتروني الذي ادخلته مرتبط بحساب اخر اذا كنت صاحب البريد ادخل على مايكورسس واختر تسجيل بالدورات .
        /// </summary>
        internal static string emailalreadyregistered {
            get {
                return ResourceManager.GetString("emailalreadyregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموظف المسؤل.
        /// </summary>
        internal static string EmployResponse {
            get {
                return ResourceManager.GetString("EmployResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد ملفات مرفوعة.
        /// </summary>
        internal static string empty {
            get {
                return ResourceManager.GetString("empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تسجيل اي حضور او غياب لك حتى الأن.
        /// </summary>
        internal static string emptya {
            get {
                return ResourceManager.GetString("emptya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاتوجد واجبات لهذه المادة.
        /// </summary>
        internal static string emptyh {
            get {
                return ResourceManager.GetString("emptyh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تحديد جدول للدرس لحد الأن.
        /// </summary>
        internal static string emptyt {
            get {
                return ResourceManager.GetString("emptyt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انهى دراسته.
        /// </summary>
        internal static string EndingStudy {
            get {
                return ResourceManager.GetString("EndingStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   أدخل  .
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أجراء خاطئ يجب ازالة الاشارة عن انتقل من جه اخرى.
        /// </summary>
        internal static string ErrorOP {
            get {
                return ResourceManager.GetString("ErrorOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير مطابقة.
        /// </summary>
        internal static string ErrorPassword {
            get {
                return ResourceManager.GetString("ErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد نتائج بحث مطابقة.
        /// </summary>
        internal static string ErrorResurch {
            get {
                return ResourceManager.GetString("ErrorResurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا بكم عزيزي الاب في شبكة  لأدارة العملية التعليمية يمكنك معنا  التوصل ومتابعة  المستوى التعليمي لولدك بكل سهولة.
        /// </summary>
        internal static string ExplainFather {
            get {
                return ResourceManager.GetString("ExplainFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض المخطط البياني يكون لكل درجة من 100 بعد تحويلها اذا كانت من نوع اقل.
        /// </summary>
        internal static string ExplainFlowChartConvert {
            get {
                return ResourceManager.GetString("ExplainFlowChartConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنهى دراسته.
        /// </summary>
        internal static string FinishedStudy {
            get {
                return ResourceManager.GetString("FinishedStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول.
        /// </summary>
        internal static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخطط بياني.
        /// </summary>
        internal static string flowChat {
            get {
                return ResourceManager.GetString("flowChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نموذج التسجيل في دورة البرمجة.
        /// </summary>
        internal static string formregiestaion {
            get {
                return ResourceManager.GetString("formregiestaion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدورات مجانية وتبقى مجانية.
        /// </summary>
        internal static string freeandstillfree {
            get {
                return ResourceManager.GetString("freeandstillfree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخر اقتراحات الأصدقاء.
        /// </summary>
        internal static string friendsComment {
            get {
                return ResourceManager.GetString("friendsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسم الكامل.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عام.
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجة من.
        /// </summary>
        internal static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجة.
        /// </summary>
        internal static string Grade1 {
            get {
                return ResourceManager.GetString("Grade1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        internal static string homeworkdetails {
            get {
                return ResourceManager.GetString("homeworkdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الواجب.
        /// </summary>
        internal static string homeworkinfo {
            get {
                return ResourceManager.GetString("homeworkinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home work titile.
        /// </summary>
        internal static string homeworktitile {
            get {
                return ResourceManager.GetString("homeworktitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الساعات.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to على سجل.
        /// </summary>
        internal static string INRecord {
            get {
                return ResourceManager.GetString("INRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النتيجة ناجح.
        /// </summary>
        internal static string IsScuess {
            get {
                return ResourceManager.GetString("IsScuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الذي يدرس في.
        /// </summary>
        internal static string ItStudyIN {
            get {
                return ResourceManager.GetString("ItStudyIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انظم الان واستمع للدروس المتبقية.
        /// </summary>
        internal static string joinnumow {
            get {
                return ResourceManager.GetString("joinnumow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العائلة.
        /// </summary>
        internal static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخر الأخبار.
        /// </summary>
        internal static string lastNews {
            get {
                return ResourceManager.GetString("lastNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يدرس الان.
        /// </summary>
        internal static string Learnmow {
            get {
                return ResourceManager.GetString("Learnmow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتقال الطلبة.
        /// </summary>
        internal static string LeavingStudnet {
            get {
                return ResourceManager.GetString("LeavingStudnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمليات.
        /// </summary>
        internal static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدارة الحسابات.
        /// </summary>
        internal static string ManageAcount {
            get {
                return ResourceManager.GetString("ManageAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدارة الدرجات.
        /// </summary>
        internal static string ManageDegress {
            get {
                return ResourceManager.GetString("ManageDegress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدارة الطلبات.
        /// </summary>
        internal static string ManageDepartmntReqest {
            get {
                return ResourceManager.GetString("ManageDepartmntReqest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأدارة.
        /// </summary>
        internal static string Managment {
            get {
                return ResourceManager.GetString("Managment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدارة الأقسام.
        /// </summary>
        internal static string ManagmentDepartment {
            get {
                return ResourceManager.GetString("ManagmentDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدرس المادة.
        /// </summary>
        internal static string MasterLearn {
            get {
                return ResourceManager.GetString("MasterLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم المدير.
        /// </summary>
        internal static string MasterName {
            get {
                return ResourceManager.GetString("MasterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير على.
        /// </summary>
        internal static string masterOf {
            get {
                return ResourceManager.GetString("masterOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى.
        /// </summary>
        internal static string MessageDetails {
            get {
                return ResourceManager.GetString("MessageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المراسلات.
        /// </summary>
        internal static string messages {
            get {
                return ResourceManager.GetString("messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        internal static string MessageStates {
            get {
                return ResourceManager.GetString("MessageStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالات التي مرت بها الرسالة.
        /// </summary>
        internal static string MessageStetus {
            get {
                return ResourceManager.GetString("MessageStetus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الرسالة.
        /// </summary>
        internal static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوزارة.
        /// </summary>
        internal static string Ministry {
            get {
                return ResourceManager.GetString("Ministry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور طويلة.
        /// </summary>
        internal static string MostThan250 {
            get {
                return ResourceManager.GetString("MostThan250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجاوزت الحروف الحد الأقصى المسموع به.
        /// </summary>
        internal static string MostThan2501 {
            get {
                return ResourceManager.GetString("MostThan2501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجاوزت الملاحظة 50 حرف يجب ان تكون اقل.
        /// </summary>
        internal static string MostThan50 {
            get {
                return ResourceManager.GetString("MostThan50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تكون الدرجة اقل من درجة الأمتحان الكلية.
        /// </summary>
        internal static string mustbelest {
            get {
                return ResourceManager.GetString("mustbelest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الاسم موجود بقاعدة البيانات.
        /// </summary>
        internal static string NameIsFound {
            get {
                return ResourceManager.GetString("NameIsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم الطالب موجود في قاعدة البيانات.
        /// </summary>
        internal static string namesStudentIsFound {
            get {
                return ResourceManager.GetString("namesStudentIsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة الجديدة.
        /// </summary>
        internal static string NewSattes {
            get {
                return ResourceManager.GetString("NewSattes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد نتائج بحث مطابقة حاول مرة اخرى وبكلمات دالة اقل أو راسل الأدارة.
        /// </summary>
        internal static string NoDataMath {
            get {
                return ResourceManager.GetString("NoDataMath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد لديك اي طلبات.
        /// </summary>
        internal static string noRequesting {
            get {
                return ResourceManager.GetString("noRequesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملاحضات/الأقتراحات.
        /// </summary>
        internal static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملاحظات.
        /// </summary>
        internal static string Notes1 {
            get {
                return ResourceManager.GetString("Notes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يحدد بعد.
        /// </summary>
        internal static string NotManageYet {
            get {
                return ResourceManager.GetString("NotManageYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الساعات.
        /// </summary>
        internal static string numberhurs {
            get {
                return ResourceManager.GetString("numberhurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الاشخاص الذين سيحضرون هذه الدورة هم.
        /// </summary>
        internal static string NumberStudents {
            get {
                return ResourceManager.GetString("NumberStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور القديمة.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور القديم غير صحيحة.
        /// </summary>
        internal static string OldPasswordUncorrect {
            get {
                return ResourceManager.GetString("OldPasswordUncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور القديمة غير صحيحة.
        /// </summary>
        internal static string OldPasswordUncorrect1 {
            get {
                return ResourceManager.GetString("OldPasswordUncorrect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط الحروف مقبولة.
        /// </summary>
        internal static string olychar {
            get {
                return ResourceManager.GetString("olychar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخص واحد.
        /// </summary>
        internal static string Oneperson {
            get {
                return ResourceManager.GetString("Oneperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط للجامعات  .
        /// </summary>
        internal static string OnlCollege {
            get {
                return ResourceManager.GetString("OnlCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسموح فقط ارقام.
        /// </summary>
        internal static string OnlyNamber {
            get {
                return ResourceManager.GetString("OnlyNamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملية.
        /// </summary>
        internal static string OpeartionAcount {
            get {
                return ResourceManager.GetString("OpeartionAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خياري.
        /// </summary>
        internal static string optional {
            get {
                return ResourceManager.GetString("optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلبات.
        /// </summary>
        internal static string OurRequesting {
            get {
                return ResourceManager.GetString("OurRequesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعد كتابة كلمة المرور الجديدة.
        /// </summary>
        internal static string PasswordEapeat {
            get {
                return ResourceManager.GetString("PasswordEapeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف شخصي.
        /// </summary>
        internal static string personalProfile {
            get {
                return ResourceManager.GetString("personalProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة الشخصية.
        /// </summary>
        internal static string PictureMe {
            get {
                return ResourceManager.GetString("PictureMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السبب.
        /// </summary>
        internal static string Reaone {
            get {
                return ResourceManager.GetString("Reaone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الطلب.
        /// </summary>
        internal static string ReciverTypeName {
            get {
                return ResourceManager.GetString("ReciverTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجل الآن.
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل.
        /// </summary>
        internal static string Record1 {
            get {
                return ResourceManager.GetString("Record1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجل تنقلات الطالب خلال دراسته.
        /// </summary>
        internal static string RecordStudentLeving {
            get {
                return ResourceManager.GetString("RecordStudentLeving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب.
        /// </summary>
        internal static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب.
        /// </summary>
        internal static string required1 {
            get {
                return ResourceManager.GetString("required1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسلسل.
        /// </summary>
        internal static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث شامل.
        /// </summary>
        internal static string SaerchAllDataBase {
            get {
                return ResourceManager.GetString("SaerchAllDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث متخصص.
        /// </summary>
        internal static string SearchExact {
            get {
                return ResourceManager.GetString("SearchExact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث عام.
        /// </summary>
        internal static string SearchGrneral {
            get {
                return ResourceManager.GetString("SearchGrneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البحث عن.
        /// </summary>
        internal static string Searchon {
            get {
                return ResourceManager.GetString("Searchon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع البحث.
        /// </summary>
        internal static string SearchType {
            get {
                return ResourceManager.GetString("SearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثانوي.
        /// </summary>
        internal static string secondary {
            get {
                return ResourceManager.GetString("secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدورة:.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select File.
        /// </summary>
        internal static string selectFile {
            get {
                return ResourceManager.GetString("selectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال الى.
        /// </summary>
        internal static string SendTo {
            get {
                return ResourceManager.GetString("SendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أظهار الملاحظات.
        /// </summary>
        internal static string ShowNotes {
            get {
                return ResourceManager.GetString("ShowNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول.
        /// </summary>
        internal static string SightIn {
            get {
                return ResourceManager.GetString("SightIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول الى النظام.
        /// </summary>
        internal static string SightIntoSystem {
            get {
                return ResourceManager.GetString("SightIntoSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل خروج.
        /// </summary>
        internal static string SiginOut {
            get {
                return ResourceManager.GetString("SiginOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string SignINadmin {
            get {
                return ResourceManager.GetString("SignINadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول.
        /// </summary>
        internal static string SignINadmin1 {
            get {
                return ResourceManager.GetString("SignINadmin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف سكايب.
        /// </summary>
        internal static string skypeID {
            get {
                return ResourceManager.GetString("skypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرحلة/الصف.
        /// </summary>
        internal static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيبدأ العام الدراسي الجديد بتاريخ.
        /// </summary>
        internal static string StartYearDays {
            get {
                return ResourceManager.GetString("StartYearDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درس في.
        /// </summary>
        internal static string StdyINTime {
            get {
                return ResourceManager.GetString("StdyINTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضافة الطالب حديثا.
        /// </summary>
        internal static string StudentAddNew {
            get {
                return ResourceManager.GetString("StudentAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجات.
        /// </summary>
        internal static string studentDegress {
            get {
                return ResourceManager.GetString("studentDegress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم الطالب.
        /// </summary>
        internal static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسماء الطلاب.
        /// </summary>
        internal static string StudentNames {
            get {
                return ResourceManager.GetString("StudentNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المواد الدراسية.
        /// </summary>
        internal static string SubjectStudy {
            get {
                return ResourceManager.GetString("SubjectStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المواد التي سيدرسها.
        /// </summary>
        internal static string SubjectWillLearn {
            get {
                return ResourceManager.GetString("SubjectWillLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجامعة/ المديرية.
        /// </summary>
        internal static string SubMinistry {
            get {
                return ResourceManager.GetString("SubMinistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        internal static string Submits {
            get {
                return ResourceManager.GetString("Submits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت المهة بنجاح.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الجدول.
        /// </summary>
        internal static string TabelName {
            get {
                return ResourceManager.GetString("TabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع عرض المخطط.
        /// </summary>
        internal static string TeypeDisplayChart {
            get {
                return ResourceManager.GetString("TeypeDisplayChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السجلات.
        /// </summary>
        internal static string theRecord {
            get {
                return ResourceManager.GetString("theRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الطالب.
        /// </summary>
        internal static string thisTudentIwont {
            get {
                return ResourceManager.GetString("thisTudentIwont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموع :.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدء نقل الطلاب.
        /// </summary>
        internal static string TravalStudnet {
            get {
                return ResourceManager.GetString("TravalStudnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to االدورة قد بدئت من تاريخ .
        /// </summary>
        internal static string tutoirlaisstarted {
            get {
                return ResourceManager.GetString("tutoirlaisstarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الدورة.
        /// </summary>
        internal static string tutorialinfo {
            get {
                return ResourceManager.GetString("tutorialinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدورة البرمجية.
        /// </summary>
        internal static string tutorialName {
            get {
                return ResourceManager.GetString("tutorialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الدرس.
        /// </summary>
        internal static string Typeclass {
            get {
                return ResourceManager.GetString("Typeclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العملية.
        /// </summary>
        internal static string Typesopeartion {
            get {
                return ResourceManager.GetString("Typesopeartion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الدراسة.
        /// </summary>
        internal static string TypeStyde {
            get {
                return ResourceManager.GetString("TypeStyde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الأمتحان.
        /// </summary>
        internal static string TypeTest {
            get {
                return ResourceManager.GetString("TypeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم موجود حاول بأسم اخر.
        /// </summary>
        internal static string UserNameExisit {
            get {
                return ResourceManager.GetString("UserNameExisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم او كلمة المرور غير صحيحة.
        /// </summary>
        internal static string UserNameOrPassworderro {
            get {
                return ResourceManager.GetString("UserNameOrPassworderro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخدام البحث المفصل.
        /// </summary>
        internal static string UsingEacatSearch {
            get {
                return ResourceManager.GetString("UsingEacatSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحذير.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا بكم عزيزي الاب في اول موقع لأدارة العملية التعليمية يمكنك التوصل الى المستوى التعليمي لولدك بكل سهولة فقط تتبع واختر مكان دراسة ولدك.
        /// </summary>
        internal static string WelcomeFather {
            get {
                return ResourceManager.GetString("WelcomeFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    مرحبا بك   .
        /// </summary>
        internal static string WelcomeMaster {
            get {
                return ResourceManager.GetString("WelcomeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماهو اقتراحك لنا. اخبرنا الأن.
        /// </summary>
        internal static string whatisyoursuggestion {
            get {
                return ResourceManager.GetString("whatisyoursuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سينتقل الى المرحلة/الصف.
        /// </summary>
        internal static string WillGoTo {
            get {
                return ResourceManager.GetString("WillGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنة.
        /// </summary>
        internal static string YearAdd {
            get {
                return ResourceManager.GetString("YearAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم/لا.
        /// </summary>
        internal static string YesNo {
            get {
                return ResourceManager.GetString("YesNo", resourceCulture);
            }
        }
    }
}
